# -*- coding: utf-8 -*-
"""Aula 4 - Juliana Camargo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRYdIGhdkPQRJ3y7jAewo_WDFaMql8ey
"""

!pip install pandas

import pandas as pd

df_diabetes = pd.read_csv("https://raw.githubusercontent.com/gazzola/pima_dataset/main/diabetes.csv")

df_diabetes

df_diabetes.head(10)

df_diabetes.info()

df_diabetes.describe()

df_diabetes.shape

"""**O DataFrame tem 768 linhas e 9 colunas.**"""

df_diabetes = df_diabetes.rename(columns={
    "Pregnancies": "Gravidez",
    "Glucose":"Glicose",
    "BloodPressure":"Pressão Arterial",
    "SkinThickness":"Espessura da Pele",
    "Insulin":"Insulina",
    "BMI":"IMC",
    "DiabetesPedigreeFunction":"Função Pedigree Diabetes",
    "Age":"Idade",
    "Outcome":"Resultado"})

#df = df.rename(columns={'oldName1': 'newName1', 'oldName2': 'newName2'})

df_diabetes.describe()

"""**Pregnancies** variable makes sense: minimum is 0 and
maximum is 17.

**Glucose** variable doesn't make sense: minimum is 0 (not possible) and maximum is 199 (normal, would qualify as pre-diabetes).
- Meaning there is an **error** in the data.

**Blood pressure** variable doesn't make sense: minimum is 0 (not possible) and maximum is 122 (normal).
- Meaning there is an **error** in the data.

**Skin thickness** variable doesn't make sense: minimum is 0 (not possible for humans) and maximum is 99 (normal).
- Meaning there is an **error** in the data.

**Insulin variable** doesn't make complete sense: minimum is 0 (technically possible but unlikely), and maximum is 846 (meaning diabetes, but normal within that range)
- Meaning there is **probably an error** in the data

**BMI** variable doesn't make sense: minimum is 0 (not possible) and maximum is 67 (would indicate obesity, but it's possible)
- Meaning there is an **error** in the data

**Diabetes Pedigree Function** variable makes sense: minimum is 0.07 and maximum is 2.42 (normal being 0 to 2.5)

**Age** variable makes sense: minimum is 21 (as the study only required woman above 21) and maximum is 81.

**Outcome** variable makes sense: as minimum is 0 and maximum is 1, the only two values it can be (has diabetes or not)
"""

analysis = {
    "Gravidez": "OK",
    "Glicose": "Analisar valor min. zero",
    "Pressão Arterial": "Analisar valor min. zero",
    "Espessura da Pele": "Analisar valor min. zero",
    "Insulina": "Analisar valor min. zero",
    "IMC": "Analisar valor min. zero",
    "Função Pedigree Diabetes": "OK",
    "Idade": "OK",
    "Resultado": "OK"}